#!/bin/sh 
PROJECT_NAME='boxen'
PROJECT_DIR='~/Code/boxen'
tmux has-session -t $PROJECT_NAME 2>/dev/null
if [ "$?" -eq 1 ] ; then
  tmux new-session -n 'editor' -s $PROJECT_NAME -d "cd $PROJECT_DIR; vim"
  tmux new-window -n 'shell' -c $PROJECT_DIR
else
  echo "Session found. Connecting."
fi
tmux attach-session -t $PROJECT_NAME
