#!/bin/sh
PROJECT_NAME='cinepresa'
PROJECT_DIR="$HOME/Code/cinepresa"
tmux has-session -t $PROJECT_NAME 2>/dev/null
if [ "$?" -eq 1 ] ; then
  tmux new-session -n 'editor' -s $PROJECT_NAME -d
  tmux send-keys -t $PROJECT_NAME:editor "cd $PROJECT_DIR; vim" C-m
  tmux new-window -n 'shell' -c $PROJECT_DIR
  tmux new-window -n 'console' -c $PROJECT_DIR
  tmux send-keys -t $PROJECT_NAME:console 'foreman run rails c' C-m
  tmux new-window -n 'database' -c $PROJECT_DIR
  tmux send-keys -t $PROJECT_NAME:database 'foreman run rails db' C-m
  tmux new-window -n 'server' -c $PROJECT_DIR
  tmux send-keys -t $PROJECT_NAME:server 'foreman run rails s' C-m
  tmux new-window -n 'log' -c $PROJECT_DIR
  tmux send-keys -t $PROJECT_NAME:log 'tail -f log/development.log' C-m
  tmux new-window -n 'foreman' -c $PROJECT_DIR
  tmux send-keys -t $PROJECT_NAME:foreman 'foreman start' C-m
  tmux select-window -t :1
else
  echo "Session found. Connecting."
fi
tmux attach-session -t $PROJECT_NAME
